# config file
tcl: "inputs/directives.tcl"
includes: "inputs/kmp/kmp_inc.txt"
orig_code: "inputs/kmp/kmp.c"
test_code: "inputs/kmp/kmp_test.txt"
top_function: "kmp"
hierarchical: True
opt_constraint: "area"
opt_constraint_tgt: 10000