# config file
tcl: "inputs/directives.tcl"
includes: "inputs/nw/nw_include.txt"
orig_code: "inputs/nw/nw.c"
test_code: "inputs/nw/nw_test.txt"
top_function: "needwun"
hierarchical: True
opt_constraint: "area"
opt_constraint_tgt: 10000