# config file
tcl: "inputs/directives.tcl"
includes: "inputs/four_parallel/include.txt"
orig_code: "inputs/four_parallel/four_parallel.c"
test_code: "inputs/four_parallel/test.txt"
top_function: "compute3"
hierarchical: True
opt_constraint: "area"
opt_constraint_tgt: 2800