# config file
tcl: "inputs/directives.tcl"
includes: "inputs/two_sequential/include.txt"
orig_code: "inputs/two_sequential/two_sequential.c"
test_code: "inputs/two_sequential/test.txt"
top_function: "compute1"
hierarchical: True
opt_constraint: "area"
opt_constraint_tgt: 4000