# config file
tcl: "inputs/directives.tcl"
includes: "inputs/two_parallel/include.txt"
orig_code: "inputs/two_parallel/two_parallel.c"
test_code: "inputs/two_parallel/test.txt"
top_function: "compute2"
hierarchical: True
opt_constraint: "area"
opt_constraint_tgt: 4000