# config file
tcl: "inputs/directives.tcl"
includes: "inputs/filter/filter_include.txt"
orig_code: "inputs/filter/filter.cpp"
test_code: "inputs/filter/filter_test.txt"
top_function: "filter"
hierarchical: True
opt_constraint: "area"
opt_constraint_tgt: 6000