# config file
tcl: "inputs/directives.tcl"
includes: "inputs/four_sequential/include.txt"
orig_code: "inputs/four_sequential/four_sequential.c"
test_code: "inputs/four_sequential/test.txt"
top_function: "compute4"
hierarchical: True
opt_constraint: "area"
opt_constraint_tgt: 4000