# config file
tcl: "inputs/directives.tcl"
includes: "inputs/repeated_four_s/include.txt"
orig_code: "inputs/repeated_four_s/repeated.c"
test_code: "inputs/repeated_four_s/test.txt"
top_function: "compute6"
hierarchical: True
opt_constraint: "area"
opt_constraint_tgt: 7000