# config file
tcl: "inputs/directives.tcl"
includes: "inputs/repeated_four_p/include.txt"
orig_code: "inputs/repeated_four_p/repeated.c"
test_code: "inputs/repeated_four_p/test.txt"
top_function: "compute5"
hierarchical: True
opt_constraint: "area"
opt_constraint_tgt: 8000